services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - 27017:27017
    restart: always
    networks:
      - springbankNet
    volumes:
      - mongodb_data_container:/data/db

  axon:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - 8024:8024
      - 8124:8124
    restart: always
    networks:
      - springbankNet

networks:
  springbankNet:
    driver: bridge

volumes:
  mongodb_data_container: {}