server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user

jwt:
  sign-key: secret-secret-secret-secret-secret-secret
  token-prefix: Token
  access-valid-time: 1
  refresh-valid-time: 10
  issuer: SpringBank