server:
  port: 9000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user

jwt:
  sign-key: secretsecretsecretsecretsecretsecret
  token-prefix: Token
  access-valid-time: 1
  refresh-valid-time: 10
  issuer: SpringBank